// Generated by https://quicktype.io

export interface Ciudad {
    region:                       Region;
    c_digo_dane_del_departamento: string;
    departamento:                 string;
    c_digo_dane_del_municipio:    string;
    municipio:                    string;
}

 enum Region {
    RegiónCaribe = "Región Caribe",
    RegiónCentroOriente = "Región Centro Oriente",
    RegiónCentroSur = "Región Centro Sur",
    RegiónEjeCafeteroAntioquia = "Región Eje Cafetero - Antioquia",
    RegiónLlano = "Región Llano",
    RegiónPacífico = "Región Pacífico",
}
